---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitlab
  namespace: gitlab
spec:
  repo: http://charts.gitlab.io/
  chart: gitlab
  version: 5.5.2
  targetNamespace: gitlab
  valuesContent: |-
    global:
      edition: ce
      extraEnv:
        PGSSLMODE: require
      hosts:
        domain: git.hannahs.family
        gitlab:
          name: git.hannahs.family
      ingress:
        configureCertmanager: false
        class: traefik
        annotations:
          kubernetes.io/tls-acme: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        provider: traefik
      psql:
        host: gitlab-postgresql
        password:
          secret: gitlab.gitlab-postgresql.credentials.postgresql.acid.zalan.do
          key: password
      minio:
        enabled: false
      appConfig:
        object_store:
          enabled: true
          connection:
            secret: minio-connection
      kas:
        enabled: true
      serviceAccount:
        enabled: true
      email:
        from: no-reply@git.hannahs.family
        reply_to: no-reply@git.hannahs.family
      smtp:
        enabled: true
        address: smtp.sendgrid.net
        port: 465
        tls: true
        user_name: apikey
        password:
          secret: gitlab-sendgrid
          key: credential
    certmanager:
      install: false
    gitlab:
      kas:
        minReplicas: 1
        maxReplicas: 1
      sidekiq:
        minReplicas: 1
        maxReplicas: 1
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
      webservice:
        minReplicas: 1
        maxReplicas: 1
        ingress:
          tls:
            secretName: gitlab-gitlab-tls
    registry:
      hpa:
        minReplicas: 1
        maxReplcias: 1
      ingress:
        tls:
          secretName: gitlab-registry-tls
    postgresql:
      install: false
    prometheus:
      install: false
    nginx-ingress:
      enabled: false
    gitlab-runner:
      unregisterRunners: true
      logLevel: debug
      runners:
        executor: kubernetes
        config: |-
          [[runners]]
            [runners.kubernetes]
              allow_privilege_escalation = true
              image = "ubuntu:18.04"
              privileged = true
            [runners.cache]
              Type = "s3"
              Path = "gitlab-runner"
              Shared = true
              [runners.cache.s3]
                ServerAddress = "minio.default"
                BucketName = "gitlab-runner-cache"
                BucketLocation = "us-east-1"
                Insecure = true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: gitlab

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: gitlab

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gitlab-sendgrid
  namespace: gitlab
spec:
  itemPath: vaults/wusn2jxjimwouyjyaqp654h7vq/items/bd6lb7pafdl5z247krfw6lztee
