---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  externalUrl: https://alerts.metrics.hannahs.family
  replicas: 1
  resources:
    limits: &resources
      cpu: 10m
      memory: 64Mi
    requests:
      <<: *resources
  serviceAccountName: alertmanager-main
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: openebs-jiva-default
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    receivers:
      - name: "null"
    route:
      group_by:
        - job
      group_interval: 5m
      group_wait: 30s
      receiver: "null"
      repeat_interval: 12h
      routes:
        - match:
            alertname: Watchdog
          receiver: "null"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-main
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 9093
      targetPort: web
  selector:
    alertmanager: main
    app: alertmanager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-main
  namespace: monitoring

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      alertmanager: main
