---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  chart: grafana
  version: 6.16.7
  targetNamespace: monitoring
  valuesContent: |-
    annotations:
      operator.1password.io/item-path: vaults/wusn2jxjimwouyjyaqp654h7vq/items/5mxdqt64tyh5em5vlx25ftfoea
      operator.1password.io/item-name: &github_secret grafana-github-auth
    image:
      tag: 8.1.5
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - &hostname monitoring.hannahs.family
      tls:
        - hosts:
            - *hostname
          secretName: *hostname
    envValueFrom:
      GF_AUTH_GITHUB_CLIENT_ID:
        secretKeyRef:
          name: *github_secret
          key: username
      GF_AUTH_GITHUB_CLIENT_SECRET:
        secretKeyRef:
          name: *github_secret
          key: credential
      GF_DATABASE_USER:
        secretKeyRef:
          name: &postgres_secret grafana.monitoring-postgresql.credentials.postgresql.acid.zalan.do
          key: username
      GF_DATABASE_PASSWORD:
        secretKeyRef:
          name: *postgres_secret
          key: password
    grafana.ini:
      database:
        type: postgres
        host: monitoring-postgresql:5432
        ssl_mode: require
      auth.github:
        enabled: true
        allow_sign_up: true
        allowed_organizations: hannahs-family
      server:
        root_url: https://monitoring.hannahs.family
    replicas: 2
    serviceMonitor:
      enabled: true
    sidecar:
      datasources:
        enabled: true
        label: grafana.com/datasource
