---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: monitoring
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki-stack
  version: 2.5.0
  targetNamespace: monitoring
  valuesContent: |-
    grafana:
      sidecar:
        datasources:
          enabled: false
    loki:
      persistence:
        enabled: true
        size: 50Gi
      podAnnotations: {}
      serviceMonitor:
        enabled: true
    promtail:
      extraVolumes:
        - name: journal
          hostPath:
            path: /var/log/journal
      extraVolumeMounts:
        - name: journal
          mountPath: /var/log/journal
          readOnly: true
      initContainer:
        enabled: true
      rbac:
        pspEnabled: true
      serviceMonitor:
        enabled: true
      extraScrapeConfigs:
        - job_name: journal
          journal:
            path: /var/log/journal
            max_age: 12h
            labels:
              job: systemd-journal
          relabel_configs:
            - source_labels:
                - __journal__systemd_unit
              target_label: unit
            - source_labels:
                - __journal__hostname
              target_label: hostname
      tolerations:
        - effect: NoSchedule
          operator: Exists

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana.com/datasource: loki
data:
  loki.yml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
