---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: monitoring-minio
  namespace: monitoring
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: monitoring-minio-console-secret
    image: minio/console:v0.6.3
    replicas: 2
    resources: {}
  credsSecret:
    name: monitoring-minio-creds-secret
  image: minio/minio:RELEASE.2021-03-01T04-20-55Z
  imagePullSecret: {}
  mountPath: /export
  pools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - monitoring-minio
              topologyKey: kubernetes.io/hostname
      resources: {}
      servers: 4
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: longhorn-minio
        status: {}
      volumesPerServer: 4
  requestAutoCert: true
