---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: monitoring-postgresql
  namespace: monitoring
spec:
  teamId: monitoring
  volume:
    size: 10Gi
    storageClass: openebs-jiva-default
  numberOfInstances: 3
  users:
    grafana: []
  databases:
    grafana: grafana
  preparedDatabases:
    grafana: {}
  postgresql:
    version: "13"
