---
- name: Install Terraform asdf plugin
  ansible.builtin.command: asdf plugin add terraform
  args:
    creates: ~/.asdf/plugins/terraform

- name: Install Terraform
  ansible.builtin.command: asdf install terraform latest
  args:
    creates: ~/.asdf/shims/terraform

- name: Use latest version of Terraform globally
  ansible.builtin.lineinfile:
    path: ~/.tool-versions
    line: terraform latest
    state: present
    create: true

- name: Install {{ shell }} shell configuration
  include_tasks: "{{ shell }}.yml"
