---
apiVersion: v1
kind: Service
metadata:
  name: mc-jbhannah-net
  namespace: minecraft
spec:
  ports:
    - name: minecraft
      port: 25565
    - name: rcon
      port: 25575

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mc-jbhannah-net
  namespace: minecraft
subsets:
  - addresses:
      - ip: 172.17.3.120
    ports:
      - name: minecraft
        port: 25565
      - name: rcon
        port: 25575

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mc-jbhannah-net
  namespace: minecraft
spec:
  entryPoints:
    - mc-jbhannah-net
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: mc-jbhannah-net
          port: 25565

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mc-jbhannah-net
  namespace: minecraft
spec:
  endpoints:
    - dnsName: _minecraft._tcp.mc.jbhannah.net
      recordType: SRV
      targets:
        - 0 0 25566 www.hannahs.family.
