---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: 1.5.3
  targetNamespace: kube-system
  valuesContent: |-
    deploymentAnnotations:
      operator.1password.io/item-path: vaults/wusn2jxjimwouyjyaqp654h7vq/items/lka26khjsd4f3kwukwcut7rq7a
      operator.1password.io/item-name: cloudflare-api
    global:
      podSecurityPolicy:
        enabled: true
    affinity: &affinity
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: cert-manager
            topologyKey: kubernetes.io/hostname
    cainjector:
      affinity:
        <<: *affinity
      extraArgs:
        - --leader-elect=false
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
      defaultIssuerGroup: cert-manager.io
    installCRDs: true
    prometheus:
      serviceMonitor:
        enabled: true
        prometheusInstance: kps-prometheus
    webhook:
      affinity:
        <<: *affinity

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed
  namespace: kube-system
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca-root
  namespace: kube-system
spec:
  isCA: true
  commonName: internal-ca
  secretName: internal-ca-root
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: self-signed
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-ca
spec:
  ca:
    secretName: internal-ca-root

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin+staging@hannahs.family
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: jesse@jbhannah.net
            apiTokenSecretRef:
              name: cloudflare-api
              key: credential

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@hannahs.family
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: jesse@jbhannah.net
            apiTokenSecretRef:
              name: cloudflare-api
              key: credential
