---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
    kubernetes.io/cluster-service: "true"
data:
  NodeHosts: |-
    172.17.3.17 tapu-koko tapu-koko.hannahs.family
    172.17.3.18 tapu-lele tapu-lele.hannahs.family
    172.17.3.19 tapu-bulu tapu-bulu.hannahs.family
    172.17.3.20 tapu-fini tapu-fini.hannahs.family
    172.17.3.120 zacien zacien.hannahs.family
    172.17.3.121 zamazenta zamazenta.hannahs.family
    172.17.3.122 eternatus eternatus.hannahs.family
  Corefile: |-
    .:53 {
        reload
        cache 30
        errors
        health
        kubernetes cluster.local
        autopath @kubernetes
        hosts /etc/coredns/NodeHosts {
          reload 1s
          fallthrough
        }
        loadbalance
        prometheus 0.0.0.0:9153
        loop
        forward . /etc/resolv.conf
    }
