---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: descheduler
  namespace: kube-system
spec:
  repo: https://kubernetes-sigs.github.io/descheduler
  chart: descheduler
  version: 0.20.0
  targetNamespace: kube-system
