---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: external-dns
  version: 5.0.0
  targetNamespace: kube-system
  valuesContent: |-
    cloudflare:
      secretName: cloudflare
    crd:
      create: true
    fqdnTemplate: "{{name}}.hannahs.family"
    logFormat: json
    metrics:
      enabled: true
      podAnnotations: {}
    provider: cloudflare
    resources:
      requests:
        cpu: 5m
        memory: 16Mi
      limits:
        cpu: 10m
        memory: 32Mi
    sources:
      - service
      - ingress
      - crd
    txtOwnerId: legendaries.hannahs.family
