---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kured
  namespace: kube-system
spec:
  repo: https://weaveworks.github.io/kured
  chart: kured
  version: 2.9.0
  targetNamespace: kube-system
  valuesContent: |-
    metrics:
      create: true
    podSecurityPolicy:
      create: true
    service:
      create: true
    tolerations:
      - effect: NoSchedule
        operator: Exists

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kured.rules
  namespace: kube-system
spec:
  groups:
    - name: kured.rules
      rules:
        - alert: RebootRequired
          annotations:
            summary: Machine(s) require being rebooted, and the reboot daemon has failed to do so for 24 hours.
            impact: Cluster nodes more vulnerable to security exploits. Eventually, no disk space left.
            description: Machine(s) require being rebooted, probably due to kernel update.
          expr: max(kured_reboot_required != 0)
          for: 24h
          labels:
            severity: warning
