---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: kube-system
spec:
  console:
    consoleSecret:
      name: minio-console-secret
    image: minio/console:v0.6.8
    replicas: 1
    resources:
      requests:
        memory: 64Mi
  credsSecret:
    name: minio-secret
  env:
    - name: MINIO_STORAGE_CLASS_STANDARD
      value: EC:4
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: public
  image: minio/minio:RELEASE.2021-04-22T15-44-28Z
  mountPath: /export
  pools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - minio
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - pool-0
              topologyKey: kubernetes.io/hostname
      name: pool-0
      resources:
        limits:
          memory: 4Gi
        requests:
          memory: 2Gi
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "10737418240"
          storageClassName: local-path
      volumesPerServer: 2
  requestAutoCert: false
  users:
    - name: minio-user-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: kube-system
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - &hostname minio.hannahs.family
      secretName: *hostname
  rules:
    - host: *hostname
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: minio
                port:
                  name: http-minio

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: kube-system
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - &hostname console.minio.hannahs.family
      secretName: *hostname
  rules:
    - host: *hostname
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: minio-console
                port:
                  name: http-console

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: minio
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - targetPort: 9000
      path: /minio/v2/metrics/node
      interval: 15s
  selector:
    matchLabels:
      v1.min.io/tenant: minio

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: minio-cluster
  namespace: kube-system
spec:
  prober:
    url: minio.kube-system
    path: /minio/v2/metrics/cluster
  targets:
    staticConfig:
      static:
        - minio.kube-system
  interval: 15s
