---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  repo: https://oauth2-proxy.github.io/manifests
  chart: oauth2-proxy
  version: 5.0.6
  targetNamespace: kube-system
  valuesContent: |-
    config:
      configFile: |-
        cookie_domains = [
          ".hannahs.family",
          ".jbhannah.net"
        ]
        email_domains = ["*"]
        github_org = "hannahs-family"
        github_team = ""
        provider = "github"
        redirect_url = "https://auth.hannahs.family/oauth2/callback"
        reverse_proxy = true
        set_authorization_header = true
        set_xauthrequest = true
        upstreams = [
          "static://202"
        ]
        whitelist_domains = [
          ".hannahs.family",
          ".jbhannah.net"
        ]
      existingSecret: oauth2-proxy
    ingress:
      annotations:
        kubernetes.io/tls-acme: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-oauth2-proxy-auth-headers@kubernetescrd
        traefik.ingress.kubernetes.io/router.priority: "101"
      enabled: true
      hosts:
        - &hostname auth.hannahs.family
      tls:
        - hosts:
            - *hostname
          secretName: *hostname
    podAnnotations:
      operator.1password.io/item-path: vaults/wusn2jxjimwouyjyaqp654h7vq/items/mevlkheef2vvcgcrdxq2ynhrjq
      operator.1password.io/item-name: oauth2-proxy
    securityContext:
      enabled: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-forward-auth
  namespace: kube-system
spec:
  forwardAuth:
    address: http://oauth2-proxy/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-auth-headers
  namespace: kube-system
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: hannahs.family
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/oauth2`)
      kind: Rule
      priority: 100
      services:
        - name: oauth2-proxy
          kind: Service
          port: 80
      middlewares:
        - name: oauth2-proxy-auth-headers

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      interval: 15s
  selector:
    matchLabels:
      app: oauth2-proxy
