---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy
  namespace: kube-system
data:
  oauth2_proxy.cfg: |
    cookie_domains = [".hannahs.family"]
    email_domains = ["*"]
    github_org = "hannahs-family"
    github_team = ""
    metrics_address = "127.0.0.1:4190"
    provider = "github"
    set_xauthrequest = true
    set_authorization_header = true
    upstreams = ["file:///dev/null"]
    whitelist_domains = [".hannahs.family"]

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  repo: https://oauth2-proxy.github.io/manifests
  chart: oauth2-proxy
  version: 3.2.10
  targetNamespace: kube-system
  valuesContent: |-
    config:
      existingConfig: oauth2-proxy
      existingSecret: oauth2-proxy
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.1.3
    ingress:
      annotations:
        kubernetes.io/tls-acme: "true"
      enabled: true
      hosts:
        - &hostname auth.hannahs.family
      tls:
        - hosts:
            - *hostname
          secretName: *hostname
    securityContext:
      enabled: true
