---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  repo: https://1password.github.io/connect-helm-charts
  chart: connect
  version: 1.6.0
  targetNamespace: onepassword
  valuesContent: |-
    connect:
      version: 1.3.1
    operator:
      autoRestart: true
      create: true
      version: 1.1.0
      watchNamespace: []
    service:
      type: ClusterIP
