# ---
# apiVersion: helm.cattle.io/v1
# kind: HelmChart
# metadata:
#   name: onepassword-connect
#   namespace: kube-system
# spec:
#   repo: https://1password.github.io/connect-helm-charts
#   chart: connect
#   version: 1.4.0
#   targetNamespace: onepassword
#   valuesContent: |-
#     connect:
#       version: 1.3.1
#     operator:
#       autoRestart: true
#       create: true
#       version: 1.0.2
#       watchNamespace: []
#     service:
#       type: ClusterIP

---
# Source: connect/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onepassword-connect-operator
  namespace: onepassword
  labels:
    helm.sh/chart: connect-1.4.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm

---
# Source: connect/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onepassword-connect-operator
  labels:
    helm.sh/chart: connect-1.4.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - onepassword-connect-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
  - apiGroups:
      - onepassword.com
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
# Source: connect/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: onepassword
  labels:
    helm.sh/chart: connect-1.4.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  selector:
    app: onepassword-connect
  ports:
    - port: 8081
      name: connect-sync
    - port: 8080
      name: connect-api

---
# Source: connect/templates/connect-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: onepassword
  labels:
    helm.sh/chart: connect-1.4.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        version: "1.3.1"
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: credentials
          secret:
            secretName: op-credentials
      initContainers:
        - name: sqlite-permissions
          image: alpine:3.12
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "mkdir -p /home/opuser/.op/data && chown -R 999 /home/opuser && chmod -R 700 /home/opuser && chmod -f -R 600 /home/opuser/.op/config || :"
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
      containers:
        - name: connect-api
          image: 1password/connect-api:1.3.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add:
                - "NET_BROADCAST"
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  name: op-credentials
                  key: 1password-credentials.json
            - name: OP_HTTP_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 15

          livenessProbe:
            httpGet:
              path: /heartbeat
              scheme: HTTP
              port: 8080
            failureThreshold: 3
            periodSeconds: 30
            initialDelaySeconds: 15

          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
        - name: connect-sync
          image: 1password/connect-sync:1.3.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add:
                - "NET_BROADCAST"
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: OP_HTTP_PORT
              value: "8081"
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  name: op-credentials
                  key: 1password-credentials.json
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15

          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8081
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 30
            initialDelaySeconds: 15

          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data

---
# Source: connect/templates/operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-operator
  namespace: onepassword
  labels:
    helm.sh/chart: connect-1.4.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onepassword-connect-operator
  template:
    metadata:
      labels:
        name: onepassword-connect-operator
    spec:
      serviceAccountName: onepassword-connect-operator
      containers:
        - name: onepassword-connect
          image: 1password/onepassword-operator:1.0.2
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          command: ["/manager"]
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "onepassword-connect-operator"
            - name: OP_CONNECT_HOST
              value: "http://onepassword-connect:8080"
            - name: POLLING_INTERVAL
              value: "10"
            - name: OP_CONNECT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onepassword-token
                  key: token
            - name: AUTO_RESTART
              value: "true"
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi

---
# Manually created ClusterRoleBinding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onepassword-connect-operator
  labels:
    app.kubernetes.io/instance: onepassword-connect
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.2.0
    helm.sh/chart: connect-1.4.0
subjects:
  - kind: ServiceAccount
    name: onepassword-connect-operator
    namespace: onepassword
roleRef:
  kind: ClusterRole
  name: onepassword-connect-operator
  apiGroup: rbac.authorization.k8s.io
