---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: external-dns
spec:
  repo: https://kubernetes-sigs.github.io/external-dns/
  chart: external-dns
  version: 1.6.0
  targetNamespace: external-dns
  valuesContent: |-
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api
            key: credential
    podAnnotations:
      operator.1password.io/item-path: vaults/wusn2jxjimwouyjyaqp654h7vq/items/lka26khjsd4f3kwukwcut7rq7a
      operator.1password.io/item-name: cloudflare-api
    provider: cloudflare
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
    sources:
      - service
      - ingress
      - crd
    txtOwnerId: kanto.external-dns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: external-dns
    meta.helm.sh/release-namespace: external-dns
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.9.0
    helm.sh/chart: external-dns-1.2.0
  name: external-dns-crd
rules:
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints/status"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: external-dns
    meta.helm.sh/release-namespace: external-dns
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.9.0
    helm.sh/chart: external-dns-1.2.0
  name: external-dns-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-crd
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: external-dns
