---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  chart: postgres-operator
  version: 1.7.1
  targetNamespace: postgres-operator
  valuesContent: |-
    configMajorVersionUpgrade:
      major_version_upgrade_mode: "manual"
      minimal_major_version: "9.6"
      target_major_version: "13"
    configKubernetes:
      cluster_domain: legendaries.hannahs.family
      enable_pod_antiaffinity: true
      enable_pod_disruption_budget: false
    configLoadBalancer:
      db_hosted_zone: db.legendaries.hannahs.family
    configDebug:
      debug_logging: false
      enable_database_access: true
    crd:
      create: false
