---
- name: Install Python 3 provider
  ansible.builtin.pip:
    name: pynvim
    virtualenv: "{{ neovim_python3_virtualenv }}"
    virtualenv_python: python3

- name: Create provider plugin directory
  ansible.builtin.file:
    path: "{{ neovim_config }}/plugin/providers"
    state: directory
    recurse: true

- name: Configure Python 3 provider
  ansible.builtin.template:
    src: providers/python3.vim.j2
    dest: "{{ neovim_config }}/plugin/providers/python3.vim"
