---
- name: Install Python 2 provider
  ansible.builtin.pip:
    name: pynvim
    virtualenv: "{{ neovim_python2_virtualenv }}"
    virtualenv_python: python2

- name: Create provider plugin directory
  ansible.builtin.file:
    path: "{{ neovim_config }}/plugin/providers"
    state: directory
    recurse: true

- name: Configure Python 2 provider
  ansible.builtin.template:
    src: providers/python2.vim.j2
    dest: "{{ neovim_config }}/plugin/providers/python2.vim"
