---
- name: Install alacritty
  ansible.builtin.package:
    name: alacritty
    state: present
  when: not ansible_system == "Darwin"
  become: "{{ package_become }}"

- name: Install alacritty
  community.general.homebrew_cask:
    name: alacritty
    state: present
  when: ansible_system == "Darwin"

- name: Copy configuration
  ansible.builtin.copy:
    src: alacritty.yml
    dest: ~/.config/alacritty.yml

- name: Install {{ shell }} shell configuration
  include_tasks: "{{ shell }}.yml"
