---
- name: Link Fish configuration
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: ~/.config/fish/{{ item.path }}
    state: link
    force: true
  with_community.general.filetree: fish/
  when: item.state == "file"

- name: Load Starship last in config.fish
  ansible.builtin.lineinfile:
    line: __starship
    path: ~/.config/fish/config.fish
