---
- name: Install Starship
  community.general.homebrew:
    name: starship
    state: present

- name: Copy starship.toml
  ansible.builtin.template:
    src: starship.toml.j2
    dest: ~/.config/starship.toml

- name: Install {{ shell }} shell configuration
  include_tasks: "{{ shell }}.yml"
