---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openebs
  namespace: kube-system
spec:
  repo: https://openebs.github.io/charts
  chart: openebs
  version: 2.8.1
  targetNamespace: openebs
  set:
    localprovisioner.enabled: "false"
