---
- name: Allow WireGuard connections from peers
  community.general.ufw:
    rule: allow
    port: "{{ wireguard[wireguard_group].port }}"
    src: "{{ hostvars[peer].ansible_host }}"
    proto: udp
  loop: "{{ groups[wireguard_group] }}"
  loop_control:
    loop_var: peer
  when: hostvars[peer].wireguard[wireguard_group] is defined and peer != inventory_hostname

- name: Install WireGuard config file
  ansible.builtin.template:
    src: interface.conf.j2
    dest: /etc/wireguard/{{ wireguard[wireguard_group].interface }}.conf
    owner: root
    group: root
    mode: 0600
  register: wg_config

- name: Enable WireGuard on startup
  ansible.builtin.service:
    name: wg-quick@{{ wireguard[wireguard_group].interface }}
    state: started
    enabled: true

- name: Allow connections over WireGuard interface
  community.general.ufw:
    rule: allow
    direction: in
    interface: "{{ wireguard[wireguard_group].interface }}"
    src: "{{ wireguard[wireguard_group].subnet }}/{{ wireguard[wireguard_group].mask }}"
