---
- name: Install kubectl and krew
  community.general.homebrew:
    name:
      - kubernetes-cli
      - krew
    state: present

- name: Install {{ shell }} shell configuration
  include_tasks: "{{ shell }}.yml"
