---
- name: Rate-limit incoming SSH connections
  become: true
  ansible.builtin.ufw:
    app: OpenSSH
    rule: limit
    state: enabled

- name: Disable root SSH logins
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*PermitRootLogin'
    line: PermitRootLogin no
  notify: Restart sshd

- name: Disable password-authenticated SSH logins
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication'
    line: PasswordAuthentication no
  notify: Restart sshd
