---
- name: Run k3s installation script
  become: true
  command: k3s-install.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_BIN_DIR: "{{ k3s_install_bin_dir }}"
    INSTALL_K3S_SYSTEMD_DIR: "{{ k3s_install_systemd_dir }}"
    INSTALL_K3S_EXEC: >
      {{ k3s_command }}
      {% for key, value in k3s_command_args.items() %}
        {% if value is not none %}
          --{{ key }}={{ value }}
          {% if key == 'node-ip' and k3s_command == 'server' %}
            --tls-san={{ value }}
          {% endif %}
        {% endif %}
      {% endfor %}
      {% for key, value in k3s_node_labels.items() %}
        --node-label={{ key }}={{ value }}
      {% endfor %}
      {% for key, value in k3s_node_taints.items() %}
        --node-taint={{ key }}={{ value }}
      {% endfor %}
      {% if k3s_cluster_init %}
        --cluster-init
      {% endif %}
      {% if k3s_command == 'server' and k3s_disable | length > 0 %}
        --disable={{ k3s_disable | join(',') }}
      {% endif %}
    INSTALL_K3S_NAME: "{{ k3s_install_name | default('', true) }}"
    INSTALL_K3S_TYPE: "{{ k3s_install_type | default('', true) }}"
    K3S_TOKEN: "{{ k3s_token | default('', true) }}"
    K3S_URL: "{{ '' if k3s_cluster_init else k3s_url }}"
  when: k3s_install_script.changed or k3s_current_version.changed or not k3s_current_install.stat.exists
