---
- name: Uninstall LXD snap
  community.general.snap:
    name: lxd
    state: absent
  become: true
  when: ansible_distribution == "Ubuntu"

- include_tasks:
    file: sysctl.yml
    apply:
      become: true

- include_tasks:
    file: ufw.yml
    apply:
      become: true
  tags:
    - ufw

- include_tasks: install.yml
  when: k3s_cluster_init
- include_tasks: install.yml
  when: not k3s_cluster_init
