---
- name: Uninstall LXD snap
  community.general.snap:
    name: lxd
    state: absent
  become: true
  when: ansible_distribution == "Ubuntu"

- ansible.builtin.include_tasks:
    file: sysctl.yml
    apply:
      become: true

- ansible.builtin.include_tasks:
    file: ufw.yml
    apply:
      become: true
  tags:
    - ufw

- ansible.builtin.include_tasks: install.yml
