---
- ansible.builtin.include_tasks:
    file: sysctl.yml
    apply:
      become: true

- ansible.builtin.include_tasks:
    file: ufw.yml
    apply:
      become: true

- name: Set k3s base path
  set_fact:
    k3s_install_base: "{{ k3s_install_bin_dir }}/{{ k3s_install_name | default('k3s', true) }}"

- name: Get k3s installation script
  become: true
  get_url:
    url: https://get.k3s.io
    dest: "{{ k3s_install_base }}-install.sh"
    mode: 0755
    owner: root
    group: root
  register: k3s_install_script

- name: Check for current k3s installation
  stat:
    path: "{{ k3s_install_base }}"
  register: k3s_current_install

- name: Get current k3s version
  shell: "{{ k3s_install_base }} --version | awk -F' ' '{ print $3 }'"
  register: k3s_current_version
  when: k3s_current_install.stat.exists
  changed_when: k3s_current_version.stdout != k3s_version

- ansible.builtin.include_tasks: install.yml
  when: k3s_cluster_init
- ansible.builtin.include_tasks: install.yml
  when: not k3s_cluster_init
