---
- name: Create DNS A records
  community.general.cloudflare_dns:
    zone: "{{ ansible_domain }}"
    record: "{{ k3s_config_server['cluster-domain'] }}"
    type: A
    value: "{{ ansible_default_ipv4.address }}"
    api_token: "{{ cloudflare_api_token }}"
    solo: false
  when: k3s_command == "server"

# TODO: enable when dual-stack networking is configured
# - name: Create DNS AAAA records
#   community.general.cloudflare_dns:
#     zone: "{{ ansible_domain }}"
#     record: "{{ k3s_config_server['cluster-domain'] }}"
#     type: AAAA
#     value: "{{ ansible_default_ipv6.address }}"
#     api_token: "{{ cloudflare_api_token }}"
#     solo: false
#   when: k3s_command == "server"

- name: Allow k3s server connections
  ufw:
    rule: allow
    port: "6443"
    proto: tcp
  when: k3s_command == "server"

- name: Allow packet routing
  ufw:
    default: allow
    direction: routed

- name: Allow inbound cluster pod traffic
  ufw:
    rule: allow
    direction: in
    interface: cni0
