---
- name: Allow k3s server connections
  ufw:
    rule: allow
    port: "6443"
    proto: tcp
  when: k3s_command == "server"

- name: Allow packet routing
  ufw:
    default: allow
    direction: routed

- name: Allow inbound cluster pod traffic
  ufw:
    rule: allow
    direction: in
    interface: cni0
