---
- name: Create ~/.config/fish directories
  ansible.builtin.file:
    path: ~/.config/fish/{{ item }}
    state: directory
  loop:
    - completions
    - conf.d
    - functions

- name: Ensure config.fish exists
  ansible.builtin.stat:
    path: ~/.config/fish/config.fish
  register: fish_config_fish

- name: Create config.fish
  ansible.builtin.file:
    path: ~/.config/fish/config.fish
    state: touch
  when: not fish_config_fish.stat.exists

- name: Link configuration files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: ~/.config/fish/{{ item.path }}
    state: link
    force: true
  with_community.general.filetree: ""
  when: item.state == "file"

- name: Install configuration from templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: ~/.config/fish/{{ item.path }}
  with_community.general.filetree: ../templates
  when: item.state == "file"
