---
- name: Install fish
  ansible.builtin.package:
    name: fish
    state: present
  become: "{{ package_become }}"

- name: Get path to fish
  ansible.builtin.command: which fish
  register: fish_path
  changed_when: false

- name: Add {{ fish_path.stdout }} to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ fish_path.stdout }}"
    state: present
  become: true

- name: Create ~/.config/fish directories
  ansible.builtin.file:
    path: ~/.config/fish/{{ item }}
    state: directory
  loop:
    - completions
    - conf.d
    - functions

- name: Copy common configuration
  ansible.builtin.copy:
    src: common/
    dest: ~/.config/fish/

- name: Copy macOS-specific configuration
  ansible.builtin.copy:
    src: Darwin/
    dest: ~/.config/fish/

- name: Apply environment template
  ansible.builtin.template:
    src: conf.d/00-env.fish.j2
    dest: ~/.config/fish/conf.d/00-env.fish
