---
- name: Install fish
  ansible.builtin.package:
    name: fish
    state: present
  become: "{{ package_become }}"

- name: Create ~/.config/fish directories
  ansible.builtin.file:
    path: ~/.config/fish/{{ item }}
    state: directory
  loop:
    - conf.d
    - functions

- name: Copy config.fish
  ansible.builtin.template:
    src: config.fish.j2
    dest: ~/.config/fish/config.fish
