---
- name: Install fish
  ansible.builtin.package:
    name: fish
    state: present
  become: "{{ package_become }}"

- name: Get path to fish
  ansible.builtin.command: which fish
  register: fish_path
  changed_when: false

- name: Add {{ fish_path.stdout }} to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ fish_path.stdout }}"
    state: present
  become: true

- name: Install Fisher
  ansible.builtin.shell: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
  args:
    creates: ~/.config/fish/functions/fisher.fish
    executable: "{{ fish_path.stdout }}"
    warn: false

- include_tasks: config.yml
