---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kubernetes
  namespace: default
  labels:
    component: apiserver
    provider: kubernetes
spec:
  entryPoints:
    - websecure
  tls:
    secretName: k3s-serving
    domains:
      - main: legendaries.hannahs.family
    passthrough: true
  routes:
    - match: HostSNI(`legendaries.hannahs.family`)
      kind: Rule
      services:
        - name: kubernetes
          port: 443

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kubernetes
  namespace: default
spec:
  endpoints:
    - dnsName: legendaries.hannahs.family
      recordType: CNAME
      targets:
        - www.hannahs.family
