---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: default
spec:
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2021-10-06T23-36-31Z
  mountPath: /export
  pools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - minio
              topologyKey: kubernetes.io/hostname
      servers: 2
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 64Gi
      volumesPerServer: 2
  requestAutoCert: false
  users:
    - name: minio
