---
- name: Install Visual Studio Code
  ansible.builtin.package:
    name: vscode
    state: present
  when: not ansible_system == "Darwin"
  become: "{{ package_become }}"

- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  when: ansible_system == "Darwin"

- name: Install {{ shell }} shell configuration
  include_tasks: "{{ shell }}.yml"
