---
- name: Install fnm
  community.general.homebrew:
    name: fnm
    state: present
  when: ansible_system == "Darwin"

- name: Install fnm
  ansible.builtin.shell: curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
  args:
    creates: ~/.fnm
  when: ansible_system == "Linux"

- name: Install {{ shell }} shell configuration
  include_tasks: "{{ shell }}.yml"
