---
- name: Install Git
  ansible.builtin.package:
    name: git
    state: present
  become: "{{ package_become }}"

- name: Copy .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Copy fish configuration
  ansible.builtin.copy:
    src: fish/
    dest: ~/.config/fish/
