---
- name: Install Git
  ansible.builtin.package:
    name: git
    state: present
  become: "{{ package_become }}"

- name: Copy .gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Install {{ shell }} shell configuration
  include_tasks: "{{ shell }}.yml"
