---
apiVersion: v1
data:
  CONSOLE_PORT: "9090"
  CONSOLE_TLS_PORT: "9443"
kind: ConfigMap
metadata:
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  name: console-env
  namespace: minio-operator

---
apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        operator.min.io/authors: MinIO, Inc.
        operator.min.io/license: AGPLv3
        operator.min.io/support: https://subnet.min.io
      name: console
      namespace: minio-operator
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: console
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          annotations:
            operator.min.io/authors: MinIO, Inc.
            operator.min.io/license: AGPLv3
            operator.min.io/support: https://subnet.min.io
          labels:
            app: console
        spec:
          containers:
            - args:
                - server
              env:
                - name: CONSOLE_OPERATOR_MODE
                  value: "on"
              image: minio/console:v0.6.8
              imagePullPolicy: IfNotPresent
              name: console
              ports:
                - containerPort: 9090
                  name: console-http
                  protocol: TCP
                - containerPort: 9443
                  name: console-https
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: console-sa
          serviceAccountName: console-sa
          terminationGracePeriodSeconds: 30
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        operator.min.io/authors: MinIO, Inc.
        operator.min.io/license: AGPLv3
        operator.min.io/support: https://subnet.min.io
      name: minio-operator
      namespace: minio-operator
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          name: minio-operator
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          annotations:
            operator.min.io/authors: MinIO, Inc.
            operator.min.io/license: AGPLv3
            operator.min.io/support: https://subnet.min.io
          labels:
            name: minio-operator
        spec:
          containers:
            - env:
                - name: CLUSTER_DOMAIN
                  value: legendaries.hannahs.family
              image: minio/operator:v4.0.9
              imagePullPolicy: IfNotPresent
              name: minio-operator
              resources:
                requests:
                  cpu: 200m
                  ephemeral-storage: 500Mi
                  memory: 256Mi
              securityContext:
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          serviceAccount: minio-operator
          serviceAccountName: minio-operator
          terminationGracePeriodSeconds: 30
kind: List

---
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        operator.min.io/authors: MinIO, Inc.
        operator.min.io/license: AGPLv3
        operator.min.io/support: https://subnet.min.io
      labels:
        name: console
      name: console
      namespace: minio-operator
    spec:
      clusterIP: 10.43.98.42
      clusterIPs:
        - 10.43.98.42
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 9090
          protocol: TCP
          targetPort: 9090
        - name: https
          port: 9443
          protocol: TCP
          targetPort: 9443
      selector:
        app: console
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        operator.min.io/authors: MinIO, Inc.
        operator.min.io/license: AGPLv3
        operator.min.io/support: https://subnet.min.io
      labels:
        name: minio-operator
      name: operator
      namespace: minio-operator
    spec:
      clusterIP: 10.43.192.174
      clusterIPs:
        - 10.43.192.174
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 4222
          protocol: TCP
          targetPort: 4222
        - name: https
          port: 4233
          protocol: TCP
          targetPort: 4233
      selector:
        name: minio-operator
      sessionAffinity: None
      type: ClusterIP
kind: List
