---
- name: Set server properties
  become: true
  lineinfile:
    create: true
    path: "{{ minecraft_home }}/server.properties"
    regexp: "^{{ item.key }} ?="
    line: "{{ item.key }}={{ (item.value | string | lower) if item.value is boolean else item.value }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  loop: "{{ minecraft_default_properties | combine(minecraft_properties) | dict2items }}"

- name: Write configuration files
  become: true
  copy:
    content: "{{ item.value }}"
    dest: "{{ minecraft_home }}/{{ item.key }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  loop: "{{ minecraft_default_configs | combine(minecraft_configs) | dict2items }}"
