---
- include_tasks: user.yml

- name: Create {{ minecraft_domain }} directory
  become: true
  file:
    path: "{{ minecraft_home }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"

- include_tasks: fabric.yml
- include_tasks: config.yml
- include_tasks: runner.yml
- include_tasks: ufw.yml
  when: minecraft_ufw
- include_tasks: systemd.yml
