---
- name: Allow Minecraft server connections
  become: true
  ufw:
    port: "'{{ (minecraft_default_properties | combine(minecraft_properties))['server-port'] }}'"
    proto: tcp
    rule: allow

- name: Allow RCON connections
  become: true
  ufw:
    port: "'{{ (minecraft_default_properties | combine(minecraft_properties))['rcon.port'] }}'"
    proto: tcp
    rule: allow
  when: (minecraft_default_properties | combine(minecraft_properties))['enable-rcon']
