---
- name: Create {{ minecraft_user }} group
  become: true
  group:
    name: "{{ minecraft_user }}"
    system: true

- name: Create {{ minecraft_user }} user
  become: true
  user:
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    system: true
    home: "{{ minecraft_home }}"
    password_lock: true
