---
- name: Set Cloudflare DNS A record
  community.general.cloudflare_dns:
    zone: "{{ ansible_domain }}"
    record: "{{ ansible_hostname }}"
    type: A
    value: "{{ ansible_default_ipv4.address }}"
    api_token: "{{ cloudflare_api_token }}"
