---
- hosts: desktop
  roles:
    - name: alacritty
      tags:
        - alacritty
    - name: vscode
      tags:
        - vscode
    - name: postgres-app
      tags:
        - postgres-app
      when: ansible_system == "Darwin"
