---
- hosts: all
  roles:
    - name: fish
      when: shell == "fish"
      tags:
        - shell
        - fish
    - name: tmux
      tags:
        - tmux
    - name: git
      tags:
        - git
    - name: starship
      tags:
        - starship
    - name: exa
      tags:
        - exa
    - name: fnm
      tags:
        - fnm
    - name: kubectl
      tags:
        - kubectl
    - name: terraform
      tags:
        - terraform
