---
- name: Base VPS setup
  ansible.builtin.import_playbook: vps.yml
  vars:
    hosts_list: legendaries
  tags:
    - base

- hosts: legendaries
  roles:
    - name: wireguard
      tags:
        - wireguard
    - name: k3s
      tags:
        - k3s
