---
- name: Base system
  ansible.builtin.import_playbook: system.yml

- name: Dotfiles
  ansible.builtin.import_playbook: dotfiles.yml

- name: Desktop
  ansible.builtin.import_playbook: desktop.yml
  when: "'desktop' in group_names"
