---
- hosts: vps
  roles:
    - name: dns
      tags:
        - dns
    - name: service_user
      tags:
        - service_user
    - name: sshd
      tags:
        - sshd

- hosts: ssdnodes
  vars:
    wireguard_group: ssdnodes
  roles:
    - name: wireguard
      tags:
        - wireguard
