---
- hosts: vps
  roles:
    - name: dns
      tags:
        - dns
    - name: service_user
      tags:
        - service_user
    - name: sshd
      tags:
        - sshd

- hosts: ssdnodes
  roles:
    - name: wireguard
      vars:
        wireguard_group: ssdnodes
      tags:
        - wireguard
