---
- hosts: "{{ hosts_list | default('vps') }}"
  roles:
    - name: apt
      tags:
        - apt
    - name: dns
      tags:
        - dns
    - name: service_user
      tags:
        - service_user
    - name: sshd
      tags:
        - sshd
