---
- name: Install aptitude
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name: apt
    state: present

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    install_recommends: false
    purge: true
    upgrade: full
    update_cache: true

- name: Check for reboot sentinel
  ansible.builtin.stat:
    path: /var/run/reboot-required
  notify: Reboot
  when: apt_reboot
