---
- name: Create {{ adoptium_user }} group
  become: true
  ansible.builtin.group:
    name: "{{ adoptium_user }}"
    system: true

- name: Create {{ adoptium_user }} user
  become: true
  ansible.builtin.user:
    name: "{{ adoptium_user }}"
    group: "{{ adoptium_user }}"
    system: true
    home: "{{ adoptium_user_home }}"
    password_lock: true
    shell: /usr/sbin/nologin

- name: Download and extract Temurin {{ adoptium_version.major }} release
  become: true
  become_user: "{{ adoptium_user }}"
  ansible.builtin.unarchive:
    creates: "{{ adoptium_user_home }}/jdk-{{ adoptium_version.major }}.{{ adoptium_version.minor }}.{{ adoptium_version.patch }}+{{ adoptium_version.rev }}"
    remote_src: true
    src: https://github.com/adoptium/temurin{{ adoptium_version.major }}-binaries/releases/download/jdk-{{ adoptium_version.major }}.{{ adoptium_version.minor }}.{{ adoptium_version.patch }}+{{ adoptium_version.rev }}/OpenJDK17U-jdk_x64_linux_hotspot_{{ adoptium_version.major }}.{{ adoptium_version.minor }}.{{ adoptium_version.patch }}_{{ adoptium_version.rev }}.tar.gz
    dest: "{{ adoptium_user_home }}"
    owner: "{{ adoptium_user }}"
    group: "{{ adoptium_user }}"
