---
- name: Install fd
  ansible.builtin.package:
    name: "{{ fd_package }}"
    state: present
  become: "{{ package_become }}"

- name: Write .fdignore entries
  ansible.builtin.lineinfile:
    create: true
    path: ~/.fdignore
    line: "{{ item }}"
  loop: "{{ query('vars', *query('varnames', '^fd_ignores.*')) | flatten | unique | sort }}"
